#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.7.2 on Thu Jan 18 16:37:44 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainView(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainView.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_copybuttons = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.button_edit = wx.Button(self, wx.ID_ANY, "&Edit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.button_edit_click, self.button_edit)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainView.__set_properties
        self.SetTitle("copyboard")
        self.SetSize((442, 398))
        self.panel_copybuttons.SetScrollRate(10, 10)
        self.button_edit.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainView.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_copybuttons = wx.BoxSizer(wx.VERTICAL)
        self.panel_copybuttons.SetSizer(self.sizer_copybuttons)
        sizer_1.Add(self.panel_copybuttons, 1, wx.EXPAND, 0)
        sizer_4.Add(self.button_edit, 0, 0, 0)
        sizer_4.Add((20, 20), 0, 0, 0)
        sizer_1.Add(sizer_4, 0, 0, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def button_edit_click(self, event):  # wxGlade: MainView.<event_handler>
        print "Event handler 'button_edit_click' not implemented!"
        event.Skip()

# end of class MainView
